### ISSUE TITLE
Exporting to PDF with numbers causing issues

### ISSUE THREAD

**Issue by Shash-Sen** [RyotaUshio/obsidian-math#236]
Hi, 
I am a newbie user of Obsidian. I was using the plugin to auto number equations and referencing. But when I export to PDF this causes issues.

Following error message in console:
" Cannot read properties of undefined (reading 'setAttribute')
    at preprocessForPdfExport (plugin:math-booster:3267:15)
    at eval (plugin:math-booster:3240:5)
    at t.postProcess (app.js:1:1297325)
    at t.<anonymous> (app.js:1:2354196)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)"

**Comment by 100jnle** [comment]
I'm having a similar issue.

I can export a PDF just fine, but no equation numbers are shown. I've tried on a new sandbox vault as well with only this plugin and mathlinks installed and the same behavior occurs.

Is anyone else able to export PDFs with equation numbering?

**Comment by yexh00** [comment]
I have the same issue and the error code I received in the console says:
plugin:math-booster:3275 TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at preprocessForPdfExport (plugin:math-booster:3267:15)
    at eval (plugin:math-booster:3240:5)
    at t.postProcess (app.js:1:1297472)
    at t.<anonymous> (app.js:1:2354364)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)

**Comment by makamto** [comment]
Same here

![Image](https://github.com/user-attachments/assets/79f1eb0b-91b6-4daf-8463-4d13a3393479)

**Comment by RehmatSChawla** [comment]
Identical issue.

**Comment by jinzx10** [comment]
Same here.

**Comment by xiespringsun** [comment]
same issue

**Comment by WANGshouming4937** [comment]
I have fixed this issue and it is currently testing normally on Obsidian 1.9.0. Because this is also my first time modifying the Obsidian plugin, there may be some imperfections. You can test it: https://github.com/WANGshouming4937/obsidian-latex-theorem-equation-referencer

**Comment by 8eardcules** [comment]
> I have fixed this issue and it is currently testing normally on Obsidian 1.9.0. Because this is also my first time modifying the Obsidian plugin, there may be some imperfections. You can test it: https://github.com/WANGshouming4937/obsidian-latex-theorem-equation-referencer

If this is now fixed, can the main plugin be updated? Would be very useful for those of us who don't have BRAT :)
